import {DB} from '../db.js';import {money,num,dateFa,esc,toast,icon,showValidationErrors,guardSubmit,todayISO,isExpenseType,isIncomeType,TRANSACTION_TYPE_LABELS} from '../utils.js';import {TRANSACTION_TYPES,toMoney,validateTransaction} from '../validators.js';import {receiptEvents,refundEvents,effectiveTimestamp,safeAmount} from '../finance.js';import {pageHeader,emptyState,openModal,closeModal} from '../components.js';
export async function renderAccounting(App,opts={}){const [rows,customers,projects,invoices,allocations]=await Promise.all([DB.all('transactions'),DB.all('customers'),DB.all('projects'),DB.all('invoices'),DB.all('paymentAllocations')]);
// Income = every real receipt exactly once (transactions + legacy invoice payments), same rule as Dashboard/Reports.
// refunds (cash handed back) reduce income; they are NOT an expense
const income=receiptEvents(invoices,rows,allocations).reduce((s,e)=>s+e.amount,0)-refundEvents(invoices,rows).reduce((s,e)=>s+e.amount,0),expense=rows.filter(x=>isExpenseType(x.type)).reduce((s,x)=>s+safeAmount(x.amount),0);
// newest by the transaction's own date (legacy rows: createdAt), then by creation time
const recent=[...rows].sort((a,b)=>(effectiveTimestamp(b)||0)-(effectiveTimestamp(a)||0)||(Number(b.createdAt)||0)-(Number(a.createdAt)||0)).slice(0,50);
App.setView(`${pageHeader('حسابداری',{action:'ثبت تراکنش',actionId:'add'})}<div class="stats-grid"><div class="card stat"><div class="stat-label">مجموع درآمد</div><div class="stat-value green">${money(income)}</div></div><div class="card stat"><div class="stat-label">مجموع هزینه</div><div class="stat-value red">${money(expense)}</div></div><div class="card stat"><div class="stat-label">خالص</div><div class="stat-value ${income-expense>=0?'green':'red'}">${money(income-expense)}</div></div></div><div class="section-title">تراکنش‌های اخیر</div><div class="list">${recent.map(x=>`<div class="list-item"><div class="list-main"><div class="list-title">${esc(x.description)}</div><div class="list-sub">${esc(TRANSACTION_TYPE_LABELS[x.type]||x.type)} ${x.party?'· '+esc(x.party):''} · ${dateFa(x.date||x.createdAt)}</div></div><div class="list-value ${isIncomeType(x.type)?'green':'red'}">${isIncomeType(x.type)?'+':'−'} ${money(x.amount)}</div></div>`).join('')||emptyState('تراکنشی ثبت نشده','درآمدها و هزینه‌های خود را ثبت کنید.','ثبت تراکنش','empty-add')}</div>`);document.getElementById('add').onclick=()=>form();document.getElementById('empty-add')?.addEventListener('click',()=>form());if(opts.newType)form(opts.newType);
 function form(presetType){const m=openModal(`<div class="modal-head"><h3>ثبت تراکنش</h3><button class="close">${icon('x','')}</button></div><form id="f" class="form-grid" novalidate><div class="field"><label>نوع</label><select name="type">${TRANSACTION_TYPES.map(t=>`<option value="${t}">${TRANSACTION_TYPE_LABELS[t]||t}</option>`).join('')}</select></div><div class="field"><label>مبلغ</label><input name="amount" autofocus type="text" inputmode="decimal"></div><div class="field"><label>پروژه</label><select name="projectId"><option value="">بدون پروژه</option>${projects.filter(p=>!p.archived).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field" id="customer-wrap"><label>مشتری</label><select name="customerId"><option value="">انتخاب مشتری</option>${customers.filter(c=>!c.archived).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>تاریخ</label><input name="date" type="date" value="${todayISO()}"></div><div class="field full"><label>شرح</label><input name="description" placeholder="مثلاً دریافت بابت فاکتور"></div><div class="field full"><button class="btn btn-primary btn-block">${icon('check','')}ثبت تراکنش</button></div></form>`);const f=m.querySelector('#f'),type=f.type,cw=m.querySelector('#customer-wrap');if(presetType&&TRANSACTION_TYPES.includes(presetType))type.value=presetType;const sync=()=>cw.hidden=type.value!=='customer_payment';type.onchange=sync;sync();
 f.onsubmit=guardSubmit(async()=>{const d=Object.fromEntries(new FormData(f));
  // customer is only meaningful for customer receipts; never let a hidden selection leak into other types
  d.customerId=d.type==='customer_payment'&&d.customerId?Number(d.customerId):null;d.projectId=d.projectId?Number(d.projectId):null;
  const v=validateTransaction(d);if(showValidationErrors(f,v))return;
  // `date` is the real financial date of the transaction; createdAt is stamped by the DB layer as the real creation time
  const row={type:d.type,amount:toMoney(d.amount),date:d.date,description:String(d.description).trim(),customerId:d.customerId,projectId:d.projectId,party:customers.find(c=>c.id===d.customerId)?.name||''};
  await DB.add('transactions',row);closeModal();toast('تراکنش ثبت شد');renderAccounting(App);});}
}
