import {DB} from '../db.js';import {money,num,dateFa,esc,toast,invoiceToImage} from '../utils.js';
export async function renderInvoices(App){
 const [rows,customers,products,services]=await Promise.all([DB.all('invoices'),DB.all('customers'),DB.all('products'),DB.all('services')]);
 App.setView(`<div class="page-title-row"><h1 class="page-title">فاکتورها</h1><button class="btn btn-primary" id="add">+ فاکتور</button></div><div class="search"><span>⌕</span><input id="search" placeholder="جستجو در فاکتورها..."></div><div class="list" id="list"></div>`);
 const draw=f=>document.getElementById('list').innerHTML=(rows.filter(x=>(String(x.number)+' '+(x.customerName||'')).includes(f||'')).sort((a,b)=>b.createdAt-a.createdAt).map(x=>`<div class="list-item"><div class="list-main"><div class="list-title">فاکتور ${num(x.number)}</div><div class="list-sub">${esc(x.customerName||'مشتری آزاد')} · ${dateFa(x.createdAt)}</div></div><div class="list-value">${money(x.total)}<br><span class="badge ${x.paid>=x.total?'badge-paid':'badge-unpaid'}">${x.paid>=x.total?'پرداخت شده':'باقی‌مانده'}</span><div class="btn-row"><button class="btn btn-secondary view-i" data-id="${x.id}">نمایش</button><button class="btn btn-danger del-i" data-id="${x.id}">حذف</button></div></div></div>`).join('')||'<div class="empty">فاکتوری ثبت نشده است.</div>');
 draw('');document.getElementById('search').oninput=e=>draw(e.target.value.trim());document.getElementById('add').onclick=()=>form();
 document.querySelectorAll('.view-i').forEach(b=>b.onclick=()=>show(rows.find(x=>x.id==b.dataset.id)));document.querySelectorAll('.del-i').forEach(b=>b.onclick=async()=>{if(confirm('فاکتور حذف شود؟')){await DB.delete('invoices',Number(b.dataset.id));toast('حذف شد');renderInvoices(App)}})
 function form(){
  const r=document.getElementById('modal-root');r.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h3>فاکتور فروش جدید</h3><button class="close">×</button></div><form id="f">
  <div class="field"><label>مشتری</label><select name="customerId"><option value="">مشتری آزاد</option>${customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div>
  <div class="section-title">اقلام فاکتور</div><div id="items"></div><button type="button" class="btn btn-secondary" id="add-item">+ افزودن کالا/خدمت</button>
  <div class="section-title">تخفیف و پرداخت</div><div class="form-grid"><div class="field"><label>تخفیف</label><input name="discount" type="number" value="0"></div><div class="field"><label>پرداخت‌شده</label><input name="paid" type="number" value="0"></div></div>
  <div class="card card-pad" style="margin-top:12px">جمع: <strong id="sum">۰ تومان</strong></div><button class="btn btn-primary" style="width:100%;margin-top:12px">ثبت فاکتور</button></form></div></div>`;
  const items=r.querySelector('#items');let n=0;
  const addItem=()=>{const id=n++;items.insertAdjacentHTML('beforeend',`<div class="card card-pad invoice-row" style="margin-bottom:8px"><div class="form-grid"><div class="field"><label>نوع</label><select class="kind"><option value="product">کالا</option><option value="service">خدمت</option></select></div><div class="field"><label>شرح</label><select class="item-select">${products.map(p=>`<option data-kind="product" data-price="${p.sellPrice||0}" value="${p.id}">${esc(p.name)}</option>`).join('')}${services.map(s=>`<option data-kind="service" data-price="${s.price||0}" value="s${s.id}">${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>تعداد</label><input class="qty" type="number" value="1" min="1"></div><div class="field"><label>قیمت واحد</label><input class="price" type="number" value="0"></div></div></div>`);const row=items.lastElementChild;const sync=()=>{const opt=row.querySelector('.item-select').selectedOptions[0];row.querySelector('.price').value=opt?.dataset.price||0;calc()};row.querySelector('.item-select').onchange=sync;row.querySelector('.qty').oninput=calc;row.querySelector('.price').oninput=calc;sync()};
  addItem();r.querySelector('#add-item').onclick=addItem;
  const calc=()=>{let s=0;items.querySelectorAll('.invoice-row').forEach(row=>s+=Number(row.querySelector('.qty').value||0)*Number(row.querySelector('.price').value||0));s=Math.max(0,s-Number(r.querySelector('[name=discount]').value||0));r.querySelector('#sum').textContent=money(s);return s};r.querySelector('[name=discount]').oninput=calc;
  r.querySelector('.close').onclick=()=>r.innerHTML='';r.querySelector('#f').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target), customerId=fd.get('customerId');const its=[...items.querySelectorAll('.invoice-row')].map(row=>{const o=row.querySelector('.item-select').selectedOptions[0];return {name:o?.textContent||'',qty:Number(row.querySelector('.qty').value||1),price:Number(row.querySelector('.price').value||0)}});const total=calc(), customer=customers.find(c=>c.id==customerId);const last=Math.max(0,...rows.map(x=>Number(x.number)||0));await DB.add('invoices',{number:last+1,customerId:customerId?Number(customerId):null,customerName:customer?.name||'',items:its,discount:Number(fd.get('discount')||0),total,paid:Number(fd.get('paid')||0),createdAt:Date.now()});r.innerHTML='';toast('فاکتور ثبت شد');renderInvoices(App)}
 }
 function show(x){const r=document.getElementById('modal-root');r.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h3>فاکتور ${num(x.number)}</h3><button class="close">×</button></div><div id="invoice-print" class="invoice-box"><div class="invoice-head"><div><div class="invoice-title">DIA BUSINESS</div><div class="invoice-number">فاکتور فروش</div></div><div>شماره: ${num(x.number)}<br>تاریخ: ${dateFa(x.createdAt)}</div></div><div class="invoice-meta">طرف حساب: <strong>${esc(x.customerName||'مشتری آزاد')}</strong></div><table class="invoice-table"><thead><tr><th>ردیف</th><th>شرح کالا / خدمت</th><th>تعداد</th><th>قیمت واحد</th><th>جمع</th></tr></thead><tbody>${x.items.map((i,k)=>`<tr><td>${num(k+1)}</td><td>${esc(i.name)}</td><td>${num(i.qty)}</td><td>${money(i.price)}</td><td>${money(i.qty*i.price)}</td></tr>`).join('')}</tbody></table><div class="invoice-total"><span>تخفیف</span><span>${money(x.discount)}</span></div><div class="invoice-total"><span>مبلغ کل</span><span>${money(x.total)}</span></div><div class="invoice-total"><span>پرداخت‌شده</span><span>${money(x.paid)}</span></div><div class="invoice-total"><span>مانده</span><span>${money(Math.max(0,x.total-x.paid))}</span></div><div style="border:1px solid #aaa;padding:18px 10px;text-align:center;margin-top:12px">از انتخاب شما سپاسگزاریم</div></div><div class="btn-row no-print" style="margin-top:12px"><button id="print" class="btn btn-primary">🖨 چاپ</button><button id="img" class="btn btn-secondary">🖼 خروجی تصویر</button></div></div></div>`;r.querySelector('.close').onclick=()=>r.innerHTML='';r.querySelector('#print').onclick=()=>window.print();r.querySelector('#img').onclick=()=>invoiceToImage(r.querySelector('#invoice-print'),'DIA-Invoice-'+x.number+'.png')}
}
