import {DB} from '../db.js';import {money,num,esc,toast,icon,showValidationErrors,guardSubmit,todayISO,newToken} from '../utils.js';import {planProductStockEdit,movementOps} from '../inventory.js';import {openStockMovementModal,openStockHistoryModal} from './stock-modal.js';import {validateProduct,findDuplicate,toMoney,toNumber} from '../validators.js';import {entityUsage} from '../finance.js';import {pageHeader,emptyState,actionMenu,openModal,closeModal,bindActionMenus,deleteOrArchive} from '../components.js';
export async function renderProducts(App,opts={}){const [rows,invoices,movements]=await Promise.all([DB.all('products'),DB.all('invoices'),DB.all('stockMovements')]);App.setView(`${pageHeader('اجناس و محصولات',{action:'کالا جدید',actionId:'add-product'})}<div class="search"><img class="icon" src="./assets/icons/search.svg" alt=""><input id="search" placeholder="جستجوی کالا..." autocomplete="off"></div><div id="list" class="list"><div class="skeleton"></div><div class="skeleton"></div></div>`);const list=document.getElementById('list');const draw=f=>{const q=(f||'').trim().toLocaleLowerCase('fa-IR');const filtered=rows.filter(x=>(`${x.name} ${x.code||''} ${x.category||''}`).toLocaleLowerCase('fa-IR').includes(q));list.innerHTML=filtered.map(x=>{const low=(x.stock||0)<=(x.minStock||0)&&(x.minStock||0)>0;return `<div class="list-item"><div class="list-main"><div class="list-title">${esc(x.name)} ${low?'<span class="badge badge-warn">موجودی کم</span>':''}</div><div class="list-sub">${esc(x.code||'بدون کد')} · ${num(x.stock||0)} ${esc(x.unit||'عدد')}${x.archived?' · آرشیو':''}</div></div><div class="list-value">${money(x.salePrice||0)}</div><button class="btn btn-ghost btn-icon" data-stock="${x.id}" aria-label="حرکت موجودی">${icon('box-plus','')}</button><button class="btn btn-ghost btn-icon" data-history="${x.id}" aria-label="گردش کالا">${icon('file-text','')}</button>${actionMenu(x.id)}</div>`}).join('')||emptyState('کالایی ثبت نشده','کالاهای پرمصرف برق را اضافه کنید.','افزودن کالا','add-empty');bindActionMenus(list,{edit:id=>form(rows.find(x=>x.id==id)),delete:id=>deleteOrArchive({store:'products',row:rows.find(x=>String(x.id)===String(id)),usage:entityUsage('product',id,{invoices,movements}),noun:'کالا',onDone:()=>renderProducts(App)})});list.querySelector('#add-empty')?.addEventListener('click',()=>form());list.querySelectorAll('[data-stock]').forEach(b=>b.onclick=()=>openStockMovementModal({productId:b.dataset.stock,onDone:()=>renderProducts(App)}));list.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>openStockHistoryModal({productId:b.dataset.history}));};draw('');document.getElementById('search').oninput=e=>draw(e.target.value);document.getElementById('add-product').onclick=()=>form();if(opts.openNew)form();
 function form(x={}){const token=newToken();const m=openModal(`<div class="modal-head"><h3>${x.id?'ویرایش کالا':'کالای جدید'}</h3><button class="close">${icon('x','')}</button></div><form id="f" class="form-grid" novalidate><div class="field full"><label>نام کالا</label><input name="name" autofocus value="${esc(x.name||'')}"></div><div class="field"><label>قیمت فروش</label><input name="salePrice" type="text" inputmode="decimal" value="${x.salePrice||0}"></div><div class="field"><label>موجودی</label><input name="stock" type="text" inputmode="decimal" value="${x.stock||0}"></div><div class="field full"><button type="button" class="details-toggle" data-toggle>نمایش جزئیات بیشتر</button></div><div class="advanced-fields field full" hidden><div class="form-grid"><div class="field"><label>کد کالا</label><input name="code" value="${esc(x.code||'')}"></div><div class="field"><label>واحد</label><input name="unit" value="${esc(x.unit||'عدد')}"></div><div class="field"><label>دسته‌بندی</label><input name="category" value="${esc(x.category||'')}"></div><div class="field"><label>قیمت خرید</label><input name="purchasePrice" type="text" inputmode="decimal" value="${x.purchasePrice||0}"></div><div class="field"><label>حداقل موجودی</label><input name="minStock" type="text" inputmode="decimal" value="${x.minStock||0}"></div><div class="field full"><label>توضیحات</label><textarea name="notes">${esc(x.notes||'')}</textarea></div></div></div><div class="field full"><div class="btn-row"><button class="btn btn-primary" name="saveMode" value="close">${icon('check','')}ذخیره و بستن</button><button class="btn btn-secondary" name="saveMode" value="next" type="submit">${icon('plus','')}ذخیره و افزودن بعدی</button></div></div></form>`);const f=m.querySelector('#f');m.querySelector('[data-toggle]').onclick=()=>{const a=m.querySelector('.advanced-fields');a.hidden=!a.hidden;m.querySelector('[data-toggle]').textContent=a.hidden?'نمایش جزئیات بیشتر':'بستن جزئیات';};f.onsubmit=guardSubmit(async e=>{const d=Object.fromEntries(new FormData(f));const v=validateProduct(d);const dups=[];
  if(findDuplicate(rows,'code',d.code,{excludeId:x.id??null,previous:x.id?x.code:undefined}))dups.push({field:'code',message:'این کد کالا قبلاً ثبت شده است.'});
  const res={valid:v.valid&&!dups.length,errors:[...v.errors,...dups]};
  const bad=showValidationErrors(f,res);
  // showValidationErrors reveals the collapsed details when an error lives there; keep the toggle label in sync
  const adv=m.querySelector('.advanced-fields');m.querySelector('[data-toggle]').textContent=adv.hidden?'نمایش جزئیات بیشتر':'بستن جزئیات';
  if(bad)return;
  // one central normalizer: prices are whole Rial, stock/minStock may be decimal; empty => 0, never NaN
  ['purchasePrice','salePrice'].forEach(k=>d[k]=toMoney(d[k]));['stock','minStock'].forEach(k=>d[k]=toNumber(d[k]));
  // stock is NEVER written blindly: the typed value is compared with the ledger and the difference is recorded as a movement
  const fm=await DB.all('stockMovements');const plan=planProductStockEdit({product:x.id?x:null,desiredStock:d.stock,movements:fm,date:todayISO(),token});
  if(!plan.ok){toast(plan.error,'error');return;}
  const row=x.id?{...x,...d,id:x.id,stock:plan.stock}:{...d,stock:plan.stock};
  if(x.id)await DB.atomic([{store:'products',action:'put',data:row},...movementOps(plan.drafts)]);
  else await DB.atomic([{store:'products',action:'add',data:row,bindKey:'p'},...plan.drafts.map(dr=>({store:'stockMovements',action:'add',data:dr,bind:{productId:'p'}}))]);
  if(e.submitter?.value==='next'&&!x.id){toast('کالا ذخیره شد؛ آماده افزودن کالای بعدی');f.reset();f.name.focus();rows.push(d);}else{closeModal();toast('کالا ذخیره شد');renderProducts(App);}});};
}
