import { DB } from '../db.js';
import { money, num, dateFa, esc, isIncomeType, isExpenseType, buildCustomerLedger, INVOICE_STATUS_LABELS, faLabel, icon } from '../utils.js';
import { INVOICE_STATUS } from '../validators.js';
import { pageHeader } from '../components.js';
import { navigate } from '../router.js';

function filterRow(dt, customerId, status, from, to, rowCustomerId, rowStatus){if(from&&dt<new Date(from).getTime())return false;if(to&&dt>new Date(to).getTime()+86399999)return false;if(customerId&&String(rowCustomerId)!==String(customerId))return false;if(status&&rowStatus!==status)return false;return true;}
const reportDefs=[
  ['sales','chart','فروش','فاکتورها، فروش، دریافت و مطالبات'],['income','wallet','درآمد','دریافت‌های ثبت‌شده'],['expense','wallet','هزینه','هزینه‌ها و پرداخت‌ها'],['debtors','users','بدهکاران','مشتریانی که مانده بدهی دارند'],['invoices','file-text','فاکتورها','جستجو و فیلتر فاکتورها'],['customer','users','صورتحساب مشتری','گردش حساب و مانده یک مشتری']
];
export async function renderReports(App, params={}){
  const [customers,invoices,transactions]=await Promise.all([DB.all('customers'),DB.all('invoices'),DB.all('transactions')]);
  App.setView(`${pageHeader('گزارش‌ها',{subtitle:'گزارش‌های کاربردی کسب‌وکار'})}<div class="reports-grid">${reportDefs.map(x=>`<button class="report-card" data-report="${x[0]}"><span class="report-icon">${icon(x[1],'')}</span><span><strong>${x[2]}</strong><small>${x[3]}</small></span><img class="report-chevron" src="./assets/icons/chevron-left.svg" alt=""></button>`).join('')}</div><div id="report-area" class="report-area"></div>`);
  const grid=document.querySelector('.reports-grid');
  const area=()=>document.getElementById('report-area');
  document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>openReport(b.dataset.report));
  const filterBar=(withStatus=true)=>`<div class="report-toolbar card card-pad"><div class="report-toolbar-head"><div><strong>فیلتر گزارش</strong><small>بازه زمانی و طرف حساب را مشخص کنید.</small></div><button class="btn btn-ghost btn-icon" id="clear-filter">${icon('x','')}</button></div><div class="form-grid"><div class="field"><label>از تاریخ</label><input type="date" id="f-from"></div><div class="field"><label>تا تاریخ</label><input type="date" id="f-to"></div><div class="field"><label>مشتری</label><select id="f-customer"><option value="">همه مشتریان</option>${customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div>${withStatus?`<div class="field"><label>وضعیت</label><select id="f-status"><option value="">همه وضعیت‌ها</option>${INVOICE_STATUS.map(s=>`<option value="${s}">${faLabel(INVOICE_STATUS_LABELS,s)}</option>`).join('')}</select></div>`:''}<div class="field full"><button class="btn btn-primary btn-block" id="apply-filter">${icon('search','')}نمایش گزارش</button></div></div></div><div id="filtered-out"></div>`;
  const readFilters=()=>({from:document.getElementById('f-from')?.value,to:document.getElementById('f-to')?.value,customerId:document.getElementById('f-customer')?.value,status:document.getElementById('f-status')?.value});
  function openReport(type){
    grid.hidden=true;
    if(type==='debtors'){debtorsReport();return;}
    if(type==='customer'){customerReport();return;}
    area().innerHTML=`<div class="report-view-head"><button class="btn btn-ghost" id="back-report">${icon('arrow-right','')}گزارش‌ها</button><div><h2>${reportDefs.find(x=>x[0]===type)?.[2]||'گزارش'}</h2><small>فیلتر و جزئیات گزارش</small></div></div>`+filterBar(type!=='income'&&type!=='expense');
    document.getElementById('apply-filter').onclick=()=>{const f=readFilters(); if(type==='sales')salesReport(f);else if(type==='income')incomeExpenseReport(f,true);else if(type==='expense')incomeExpenseReport(f,false);else invoicesReport(f);};
    document.getElementById('back-report').onclick=()=>showReportHome();
    document.getElementById('clear-filter').onclick=()=>openReport(type);
    document.getElementById('apply-filter').click();
  }
  function summaryCards(cards){return `<div class="report-summary-grid">${cards.map(c=>`<div class="report-summary-card"><small>${c[0]}</small><strong class="${c[2]||''}">${c[1]}</strong></div>`).join('')}</div>`;}
  function salesReport(f){const rows=invoices.filter(i=>i.status!=='cancelled'&&filterRow(i.createdAt,f.customerId,f.status,f.from,f.to,i.customerId,i.status));const total=rows.reduce((s,i)=>s+(i.total||0),0),paid=rows.reduce((s,i)=>s+(i.paidAmount||0),0);document.getElementById('filtered-out').innerHTML=summaryCards([['تعداد فاکتور',num(rows.length)],['فروش کل',money(total)],['دریافت‌شده',money(paid),'green'],['مطالبات',money(Math.max(0,total-paid)),'red']])+`<div class="section-title">فاکتورهای این گزارش</div><div class="report-list">${rows.sort((a,b)=>b.createdAt-a.createdAt).map(invoiceRow).join('')||'<div class="empty">موردی پیدا نشد.</div>'}</div>`;bindInvoiceRows();}
  function incomeExpenseReport(f,wantIncome){
    const tx=transactions.filter(t=>(wantIncome?isIncomeType(t.type):isExpenseType(t.type))&&filterRow(t.createdAt,f.customerId,null,f.from,f.to,t.customerId,null)).map(t=>({date:t.createdAt,description:t.description||'بدون شرح',amount:Number(t.amount)||0,type:t.type}));
    if(wantIncome){invoices.filter(i=>i.status!=='cancelled'&&Number(i.paidAmount)>0&&filterRow(i.createdAt,f.customerId,null,f.from,f.to,i.customerId,null)).forEach(i=>tx.push({date:i.updatedAt||i.createdAt,description:`دریافت فاکتور ${i.number}`,amount:Number(i.paidAmount)||0,type:'invoice_payment',invoiceId:i.id}));}
    const rows=tx.sort((a,b)=>b.date-a.date), total=rows.reduce((s,t)=>s+t.amount,0);document.getElementById('filtered-out').innerHTML=summaryCards([['تعداد تراکنش',num(rows.length)],['مجموع',money(total),wantIncome?'green':'red']])+`<div class="section-title">جزئیات</div><div class="report-list">${rows.map(t=>t.invoiceId?`<button class="report-row report-row-button" data-invoice="${t.invoiceId}"><span class="report-row-icon">${icon('file-text','')}</span><span><strong>${esc(t.description)}</strong><small>${dateFa(t.date)} · دریافت فاکتور</small></span><b class="green">${money(t.amount)}</b></button>`:`<article class="report-row"><span class="report-row-icon">${icon('wallet','')}</span><span><strong>${esc(t.description)}</strong><small>${dateFa(t.date)}</small></span><b class="${wantIncome?'green':'red'}">${money(t.amount)}</b></article>`).join('')||'<div class="empty">موردی یافت نشد.</div>'}</div>`;}
  function debtorsReport(){const list=customers.map(c=>{const bal=buildCustomerLedger(invoices,transactions,c.id).balance;return{c,bal};}).filter(x=>x.bal>0).sort((a,b)=>b.bal-a.bal);const total=list.reduce((s,x)=>s+x.bal,0);area().innerHTML=`<div class="report-view-head"><button class="btn btn-ghost" id="back-report">${icon('arrow-right','')}گزارش‌ها</button><div><h2>گزارش بدهکاران</h2><small>مشتریان دارای مانده بدهی</small></div></div>${summaryCards([['تعداد بدهکاران',num(list.length)],['مجموع مطالبات',money(total),'red']])}<div class="report-list">${list.map(x=>`<button class="report-row report-row-button" data-customer="${x.c.id}"><span class="client-avatar small">${esc(x.c.name.charAt(0))}</span><span><strong>${esc(x.c.name)}</strong><small>مشاهده گردش حساب</small></span><b class="red">${money(x.bal)}</b></button>`).join('')||'<div class="empty">بدهکاری ثبت نشده است.</div>'}</div>`;document.getElementById('back-report').onclick=()=>showReportHome();document.querySelectorAll('[data-customer]').forEach(b=>b.onclick=()=>navigate('#/customers/'+b.dataset.customer));}
  function invoicesReport(f){const rows=invoices.filter(i=>filterRow(i.createdAt,f.customerId,f.status,f.from,f.to,i.customerId,i.status)).sort((a,b)=>b.createdAt-a.createdAt);document.getElementById('filtered-out').innerHTML=summaryCards([['تعداد',num(rows.length)],['مجموع',money(rows.reduce((s,i)=>s+(i.total||0),0))]])+`<div class="report-list">${rows.map(invoiceRow).join('')||'<div class="empty">فاکتوری یافت نشد.</div>'}</div>`;bindInvoiceRows();}
  function invoiceRow(i){return `<button class="report-row report-row-button" data-invoice="${i.id}"><span class="report-row-icon">${icon('file-text','')}</span><span><strong>فاکتور ${esc(i.number)}</strong><small>${esc(i.customerName||'مشتری آزاد')} · ${dateFa(i.date||i.createdAt)} · ${faLabel(INVOICE_STATUS_LABELS,i.status)}</small></span><b>${money(i.total)}</b></button>`;}
  function bindInvoiceRows(){document.querySelectorAll('[data-invoice]').forEach(b=>b.onclick=()=>navigate('#/invoices/'+b.dataset.invoice));}
  function customerReport(){area().innerHTML=`<div class="report-view-head"><button class="btn btn-ghost" id="back-report">${icon('arrow-right','')}گزارش‌ها</button><div><h2>صورتحساب مشتری</h2><small>مانده و گردش حساب</small></div></div><div class="card card-pad"><div class="field"><label>مشتری</label><select id="cr"><option value="">انتخاب مشتری</option>${customers.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div id="crout"></div></div>`;document.getElementById('back-report').onclick=()=>showReportHome();document.getElementById('cr').onchange=e=>{const c=customers.find(x=>String(x.id)===String(e.target.value));const acc=c?buildCustomerLedger(invoices,transactions,c.id):null;const its=acc?.invoices||[];const total=acc?.total||0,paid=acc?.paid||0;document.getElementById('crout').innerHTML=c?`${summaryCards([['فاکتورها',num(its.length)],['کل',money(total)],['پرداخت',money(paid),'green'],['مانده',money(Math.max(0,total-paid)),'red']])}<div class="report-list">${its.sort((a,b)=>b.createdAt-a.createdAt).map(invoiceRow).join('')||'<div class="empty">فاکتوری ندارد.</div>'}</div><button class="btn btn-secondary btn-block mt-3" id="open-full">مشاهده صفحه کامل مشتری</button>`:'';bindInvoiceRows();document.getElementById('open-full')?.addEventListener('click',()=>navigate('#/customers/'+c.id));};}
  function showReportHome(){grid.hidden=false;area().innerHTML='';window.scrollTo(0,0);}
  const initial=params.query?.get('type'); if(initial)openReport(initial);
}
