import {DB,exportDatabase,importDatabase,validateBackup,getSettings,saveSettings,stores} from '../db.js';import {downloadJSON,toast,esc,num,icon,showValidationErrors,guardSubmit} from '../utils.js';import {validateSettings,toNumber} from '../validators.js';import {pageHeader} from '../components.js';
export async function renderSettings(App){const s=await getSettings();App.setView(`${pageHeader('تنظیمات',{back:true})}<div class="list"><div class="card card-pad"><h3>اطلاعات کسب‌وکار</h3><form id="business-form" class="form-grid" novalidate><div class="field full"><label>نام کسب‌وکار</label><input name="businessName" autofocus value="${esc(s.businessName)}"></div><div class="field"><label>نام صاحب کسب‌وکار</label><input name="ownerName" value="${esc(s.ownerName)}"></div><div class="field"><label>شماره تماس</label><input name="phone" inputmode="tel" value="${esc(s.phone)}"></div><div class="field"><label>ایمیل</label><input name="email" type="email" value="${esc(s.email||'')}"></div><div class="field full"><label>آدرس</label><textarea name="address">${esc(s.address)}</textarea></div><div class="field full"><label>توضیحات پایین فاکتور</label><textarea name="invoiceNote">${esc(s.invoiceNote)}</textarea></div><div class="field full"><button class="btn btn-primary">${icon('check','')}ذخیره اطلاعات</button></div></form></div><div class="card card-pad"><h3>فاکتور</h3><form id="invoice-form" class="form-grid" novalidate><div class="field"><label>واحد مبالغ</label><input value="ریال" disabled></div><div class="field"><label>پیشوند شماره</label><input name="invoicePrefix" value="${esc(s.invoicePrefix)}" placeholder="مثلاً INV-"></div><div class="field"><label>شماره شروع</label><input name="invoiceStartNumber" type="text" inputmode="numeric" value="${num(s.invoiceStart)}"></div><div class="field"><label>مالیات</label><select name="taxEnabled"><option value="0" ${!s.taxEnabled?'selected':''}>غیرفعال</option><option value="1" ${s.taxEnabled?'selected':''}>فعال</option></select></div><div class="field"><label>درصد مالیات</label><input name="taxRate" type="text" inputmode="decimal" value="${num(s.taxPercent)}"></div><div class="field full"><button class="btn btn-primary">${icon('check','')}ذخیره تنظیمات فاکتور</button></div></form></div><div class="card card-pad"><h3>پشتیبان‌گیری</h3><p class="hint">اطلاعات روی همین دستگاه ذخیره می‌شود. بکاپ JSON را مرتب در یک محل امن نگه دارید.</p><div class="btn-row"><button class="btn btn-primary" id="export">${icon('download','')}خروجی پشتیبان</button><label class="btn btn-secondary" for="import">${icon('upload','')}بازیابی</label><input id="import" type="file" accept=".json,application/json" hidden></div></div><div class="card card-pad"><h3>اطلاعات برنامه</h3><p class="hint">نسخه V2.8 Phase 1 (Financial Integrity) · Offline First · Vanilla JS · IndexedDB · PWA · GitHub Pages · مبالغ به ریال</p></div><div class="card card-pad"><h3>حذف اطلاعات</h3><p class="danger-note">قبل از حذف حتماً یک نسخه پشتیبان بگیرید.</p><button class="btn btn-danger" id="clear">حذف تمام اطلاعات</button></div></div>`);document.querySelector('[data-back]')?.addEventListener('click',()=>history.length>1?history.back():location.hash='#/dashboard');
 const bf=document.getElementById('business-form');bf.onsubmit=guardSubmit(async()=>{const d=Object.fromEntries(new FormData(bf));const v=validateSettings(d);if(showValidationErrors(bf,v))return;await saveSettings(d);toast('اطلاعات کسب‌وکار ذخیره شد');});const inf=document.getElementById('invoice-form');inf.onsubmit=guardSubmit(async()=>{const fd=Object.fromEntries(new FormData(inf));
  // validate the RAW text (Persian/Arabic digits, ٬ separators and ٫ decimal are all understood), then convert once, centrally
  const v=validateSettings({...fd,taxEnabled:fd.taxEnabled==='1'});if(showValidationErrors(inf,v))return;
  const taxRate=toNumber(fd.taxRate,0),start=Math.round(toNumber(fd.invoiceStartNumber,1001));
  const d={...fd,taxEnabled:fd.taxEnabled==='1',taxRate,taxPercent:taxRate,invoiceStartNumber:start,invoiceStart:start};
  await saveSettings(d);toast('تنظیمات فاکتور ذخیره شد');});document.getElementById('export').onclick=async()=>{downloadJSON(await exportDatabase(),'DIA-Backup-'+new Date().toISOString().slice(0,10)+'.json');toast('پشتیبان آماده شد');};document.getElementById('import').onchange=async e=>{const input=e.target;const file=input.files?.[0];if(!file)return;try{
  // 1) parse + validate completely BEFORE anything can be touched; an invalid file never reaches the database
  let d;try{d=JSON.parse(await file.text());}catch(_){throw new Error('فایل پشتیبان معتبر نیست (JSON نامعتبر).');}
  const check=validateBackup(d);if(!check.valid)throw new Error(check.errors.join(' — '));
  const c=check.counts;const summary=`مشتری: ${c.customers||0} · کالا: ${c.products||0} · خدمت: ${c.services||0} · پروژه: ${c.projects||0} · فاکتور: ${c.invoices||0} · تراکنش: ${c.transactions||0} · حرکت موجودی: ${c.stockMovements||0} · تخصیص: ${c.paymentAllocations||0}`;
  // 2) only after explicit confirmation is the (atomic, all-or-nothing) restore executed
  if(confirm(`فایل پشتیبان معتبر است:\n${summary}\n\nاطلاعات فعلی با پشتیبان جایگزین شود؟`)){await importDatabase(d);toast('بازیابی انجام شد');renderSettings(App);}
}catch(err){toast(err.message||'فایل پشتیبان معتبر نیست.','error');}finally{input.value='';}};document.getElementById('clear').onclick=async()=>{if(confirm('همه اطلاعات حذف شود؟')){if(confirm('این عملیات غیرقابل بازگشت است. ادامه می‌دهید؟')){for(const st of stores)await DB.clear(st);toast('اطلاعات حذف شد');renderSettings(App);}}};}
